name: eval
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cudatoolkit=11.3
  - pip:
      - bert-score==0.3.13
      - rouge-score==0.1.2
      - transformers==4.46.3
      - scikit-learn==1.5.2
      # - phonetic-word-embedding @ git+https://github.com/<repository>
      - filelock
      - pronouncing==0.2.0
