name: unsloth_env
channels:
  - pytorch
  - nvidia
  - xformers
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda=12.1
  - cudatoolkit
  - xformers
  - pip
  - pip:
      - "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
      - bert-score
      - rouge-score
      - scikit-learn
      - trl
      - peft
      - accelerate
      - bitsandbytes